CREATE TABLE budgyscheme.account
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    username   VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE budgyscheme.category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    code       VARCHAR(255),
    account_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE budgyscheme.tbank_import
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    transaction_count INTEGER,
    saved             INTEGER,
    skipped           INTEGER,
    status            SMALLINT,
    CONSTRAINT pk_tbankimport PRIMARY KEY (id)
);

CREATE TABLE budgyscheme.tbank_transaction
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    import_id                BIGINT                                  NOT NULL,
    operation_date           TIMESTAMP WITHOUT TIME ZONE,
    payment_date             date,
    card_number              VARCHAR(255),
    status                   VARCHAR(255),
    operation_amount         DECIMAL,
    operation_currency       VARCHAR(255),
    payment_amount           DECIMAL,
    payment_currency         VARCHAR(255),
    cashback                 DECIMAL,
    category                 VARCHAR(255),
    mcc                      INTEGER,
    description              VARCHAR(255),
    bonuses                  DECIMAL,
    investment_rounding      DECIMAL,
    rounded_operation_amount DECIMAL,
    row_hash                 INTEGER,
    CONSTRAINT pk_tbanktransaction PRIMARY KEY (id)
);

CREATE TABLE budgyscheme.transaction
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    amount      DECIMAL,
    description VARCHAR(255),
    type        SMALLINT,
    category_id BIGINT                                  NOT NULL,
    account_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);