CREATE TABLE budgyscheme.transaction
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    amount      DECIMAL,
    description VARCHAR(255),
    type        SMALLINT,
    category_id BIGINT                                  NOT NULL,
    account_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

ALTER TABLE budgyscheme.transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES budgyscheme.account (id);

ALTER TABLE budgyscheme.transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES budgyscheme.category (id);